// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcFWE8XFbs2K2VBv_dh67aWpiyqUryWDM',
    appId: '1:869155026844:web:75997eeaf9bc7637befa59',
    messagingSenderId: '869155026844',
    projectId: 'chat-app-fe3a6',
    authDomain: 'chat-app-fe3a6.firebaseapp.com',
    storageBucket: 'chat-app-fe3a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ4LLjZCZlTkGUTZaDClZH8pLFbnQxyB4',
    appId: '1:869155026844:android:deddbc8384823e48befa59',
    messagingSenderId: '869155026844',
    projectId: 'chat-app-fe3a6',
    storageBucket: 'chat-app-fe3a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_WK0w-9pV6Cne_J7qYj3JDPJ2fyOQrlI',
    appId: '1:869155026844:ios:80224bac4f813912befa59',
    messagingSenderId: '869155026844',
    projectId: 'chat-app-fe3a6',
    storageBucket: 'chat-app-fe3a6.appspot.com',
    iosBundleId: 'com.example.secureChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_WK0w-9pV6Cne_J7qYj3JDPJ2fyOQrlI',
    appId: '1:869155026844:ios:80224bac4f813912befa59',
    messagingSenderId: '869155026844',
    projectId: 'chat-app-fe3a6',
    storageBucket: 'chat-app-fe3a6.appspot.com',
    iosBundleId: 'com.example.secureChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcFWE8XFbs2K2VBv_dh67aWpiyqUryWDM',
    appId: '1:869155026844:web:7e13af6176a11d14befa59',
    messagingSenderId: '869155026844',
    projectId: 'chat-app-fe3a6',
    authDomain: 'chat-app-fe3a6.firebaseapp.com',
    storageBucket: 'chat-app-fe3a6.appspot.com',
  );
}
